export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const SORT_POSTS = 'SORT_POSTS';
export const POST_VOTE_REQUEST = 'VOTE_REQUEST';
export const POST_VOTE_FAILURE = 'VOTE_FAILURE';
export const POST_VOTE_SUCCESS = 'VOTE_SUCCESS';


