export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const SORT_COMMENTS = 'SORT_COMMENTS';
export const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
export const COMMENT_VOTE_FAILURE = 'COMMENT_VOTE_FAILURE';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
